SELECT 
	X.SABOR,
    X.ANO,
    X.VENDAS_SABOR AS VENDAS,
    CONCAT(ROUND((X.VENDAS_SABOR / Y.VENDAS_2016) * 100, 2), '%') AS PARTICIPAÇÃO
FROM
(SELECT
	p.SABOR,
    YEAR(n.DATA_VENDA) AS ANO,
    SUM(i.QUANTIDADE) AS VENDAS_SABOR
FROM itens_notas_fiscais i
INNER JOIN notas_fiscais n
ON n.NUMERO = i.NUMERO
INNER JOIN tabela_de_produtos p
ON i.CODIGO_DO_PRODUTO = p.CODIGO_DO_PRODUTO
GROUP BY SABOR, ANO
HAVING ANO = 2016) AS X
INNER JOIN
(SELECT
    YEAR(n.DATA_VENDA) AS ANO,
    SUM(i.QUANTIDADE) AS VENDAS_2016
FROM itens_notas_fiscais i
INNER JOIN notas_fiscais n
ON n.NUMERO = i.NUMERO
INNER JOIN tabela_de_produtos p
ON i.CODIGO_DO_PRODUTO = p.CODIGO_DO_PRODUTO
GROUP BY ANO
HAVING ANO = 2016) AS Y
ON X.ANO = Y.ANO
ORDER BY (X.VENDAS_SABOR / Y.VENDAS_2016) * 100 DESC;


