#MECANISMO PADRÃO INNODB
CREATE TABLE DEFAULT_TABLE(
	ID 		INTEGER,
    NOME	VARCHAR(100)
);

CREATE TABLE DEFAULT_TABLE(
	ID 		INTEGER,
    NOME	VARCHAR(100)
) ENGINE MyISAM;

CREATE TABLE DEFAULT_TABLE(
	ID 		INTEGER,
    NOME	VARCHAR(100)
) ENGINE MEMORY;
