#PLANO DE EXECUÇÃO -- COMANDO EXPLAIN - ÍNDICES MELHORAM O TEMPO DE EXECUÇÃO DO PLANO DE EXECUÇÃO
/*	POR LINHA DE COMANDO - DENTRO DO MYSQL

EXPLAIN SELECT A.NOME_DO_PRODUTO FROM tabela_de_produtos A \G

EXPLAIN FORMAT=JSON SELECT A.NOME_DO_PRODUTO FROM tabela_de_produtos A \G
3.75

EXPLAIN FORMAT=JSON SELECT A.NOME_DO_PRODUTO, B.QUANTIDADE, YEAR(C.DATA_VENDA) AS ANO FROM tabela_de_produtos A INNER JOIN itens_notas_fiscais B ON A.CODIGO_DO_PRODUTO = B.codigo_do_produto INNER JOIN notas_fiscais C ON B.NUMERO = C.NUMERO \G
76517.94

EXPLAIN FORMAT=JSON SELECT	A.NOME_DO_PRODUTO, SUM(B.QUANTIDADE) AS QUANTIDADE, YEAR(C.DATA_VENDA) AS ANO FROM tabela_de_produtos A INNER JOIN itens_notas_fiscais B ON A.CODIGO_DO_PRODUTO = B.codigo_do_produto INNER JOIN notas_fiscais C ON B.NUMERO = C.NUMERO GROUP BY A.NOME_DO_PRODUTO, ANO ORDER BY A.NOME_DO_PRODUTO, ANO \G
260242.51

EXPLAIN FORMAT=JSON SELECT	A.NOME_DO_PRODUTO, SUM(B.QUANTIDADE) AS QUANTIDADE, YEAR(C.DATA_VENDA) AS ANO FROM tabela_de_produtos A INNER JOIN itens_notas_fiscais B ON A.CODIGO_DO_PRODUTO = B.codigo_do_produto INNER JOIN notas_fiscais C ON B.NUMERO = C.NUMERO \G
260242.51 -> GROUP BY E ORDER BY NÃO INTERFEREM NA PERFORMANCE
*/

#mysqlslap - SIMULADOR DE DESEMPENHO DE QUERIES

/*	POR LINHA DE COMANDO - DENTRO DO MYSQL
	MYSQLSLAP -uroot -p --concurrency-100 --iteractions-10 --create-schema-sucos-vendas
    --query="SELECT* FROM notas_fiscais WHERE DATA_VENDA = '20170101'";
    
    RETORNA O TEMPO MÍNIMO, O TEMPO MÁXIMO E O TEMPO MÉDIO DE CONCLUSÃO DA QUERY
*/

SELECT
	A.NOME_DO_PRODUTO
FROM tabela_de_produtos A;

SELECT
	A.NOME_DO_PRODUTO,
    B.QUANTIDADE,
    YEAR(C.DATA_VENDA) AS ANO
FROM tabela_de_produtos A
INNER JOIN itens_notas_fiscais B
ON A.CODIGO_DO_PRODUTO = B.codigo_do_produto
INNER JOIN notas_fiscais C
ON B.NUMERO = C.NUMERO;

SELECT
	A.NOME_DO_PRODUTO,
    SUM(B.QUANTIDADE) AS QUANTIDADE,
    YEAR(C.DATA_VENDA) AS ANO
FROM tabela_de_produtos A
INNER JOIN itens_notas_fiscais B
ON A.CODIGO_DO_PRODUTO = B.codigo_do_produto
INNER JOIN notas_fiscais C
ON B.NUMERO = C.NUMERO
GROUP BY A.NOME_DO_PRODUTO, ANO
ORDER BY A.NOME_DO_PRODUTO, ANO;