#HOJE
SELECT CURDATE();

#FORMATAÇÃO - https://www.w3schools.com/sql/func_mysql_date_format.asp
SELECT DATE_FORMAT(CURDATE(), '%d/%m/%Y') AS HOJE_FORMATADO;
SELECT DATE_FORMAT(CURDATE(), '%d-%m-%Y') AS HOJE_FORMATADO;

#AGORA
SELECT CURRENT_TIMESTAMP();
SELECT CURRENT_TIME();

#AMANHÃ / ONTEM
SELECT ADDDATE(CURRENT_TIMESTAMP(), 1);
SELECT ADDDATE(CURRENT_TIMESTAMP(), -1);

#DAQUI A POUCO / UM POUCO ANTES -> EM SEGUNDOS
SELECT ADDTIME(CURRENT_TIMESTAMP(), 20000);
SELECT ADDTIME(CURRENT_TIMESTAMP(), -20000);

#ATÉ - QUANTO SE PASSOU
SELECT DATEDIFF(CURDATE(), ADDDATE(CURDATE(), 10));
SELECT DATEDIFF(CURDATE(), '2000-09-30');
SELECT DATEDIFF(ADDDATE(CURDATE(), 10), CURDATE());


#DIA - DIA DA SEMANA
SELECT DAY(CURDATE());
SELECT DAYNAME(CURDATE());

#MES - NOME DO MES
SELECT MONTH(CURDATE());
SELECT MONTHNAME(CURDATE());

#ANO
SELECT YEAR(CURDATE());

# Calculando idade na raça
SET @vData1 = CURDATE();
SET @vData2 = '2000-11-14';
SET @vDif = (CASE 
		WHEN MONTH(@vData1) > MONTH(@vData2) THEN 0
        WHEN MONTH(@vData1) < MONTH(@vData2) THEN 1
        ELSE
			CASE 
				WHEN DAY(@vData1) > DAY(@vData2) THEN 0
				ELSE 1
			END
	END); 
SELECT (YEAR(@vData1) - YEAR(@vData2) - @vDif) AS Idade;

#CALCULAR IDADE
SELECT TIMESTAMPDIFF(YEAR, @vData2, @vData1);