#HOJE
SELECT CURDATE();

#FORMATAÇÃO - https://www.w3schools.com/sql/func_mysql_date_format.asp
SELECT DATE_FORMAT(CURDATE(), '%d/%m/%Y') AS HOJE_FORMATADO;
SELECT DATE_FORMAT(CURDATE(), '%d-%m-%Y') AS HOJE_FORMATADO;

#AGORA
SELECT CURRENT_TIMESTAMP();
SELECT CURRENT_TIME();

#AMANHÃ / ONTEM
SELECT ADDDATE(CURRENT_TIMESTAMP(), 1);
SELECT ADDDATE(CURRENT_TIMESTAMP(), -1);

#DAQUI A POUCO / UM POUCO ANTES -> EM SEGUNDOS
SELECT ADDTIME(CURRENT_TIMESTAMP(), 20000);
SELECT ADDTIME(CURRENT_TIMESTAMP(), -20000);

#ATÉ - QUANTO SE PASSOU
SELECT DATEDIFF(CURDATE(), ADDDATE(CURDATE(), 10));
SELECT DATEDIFF(CURDATE(), '2000-09-30');
SELECT DATEDIFF(ADDDATE(CURDATE(), 10), CURDATE());


#DIA - DIA DA SEMANA
SELECT DAY(CURDATE());
SELECT DAYNAME(CURDATE());

#MES - NOME DO MES
SELECT MONTH(CURDATE());
SELECT MONTHNAME(CURDATE());

#ANO
SELECT YEAR(CURDATE());