SELECT
	TB_VENDAS.ID_VENDEDOR,
    TB_VENDEDORES.NOME_VENDEDOR,
    sum(TB_VENDAS.QTD_VENDIDA)
FROM TB_VENDAS, TB_VENDEDORES
WHERE TB_VENDAS.ID_VENDEDOR = TB_VENDEDORES.ID_VENDEDOR
GROUP BY TB_VENDAS.ID_VENDEDOR, TB_VENDEDORES.NOME_VENDEDOR;

SELECT
	VA.ID_VENDEDOR,
    VO.NOME_VENDEDOR,
    sum(VA.QTD_VENDIDA)
FROM TB_VENDAS VA
INNER JOIN TB_VENDEDORES VO
ON VA.ID_VENDEDOR = VO.ID_VENDEDOR
GROUP BY VA.ID_VENDEDOR, VO.NOME_VENDEDOR;
